### PR TITLE
Fix config path

### LINKED ISSUE #25: Incorrect config file path fetch
Syncron is currently only looking for config file on the current path where syncron is executed.

### PR DESCRIPTION
**Pull request by IgnacioPro**
This PR fixes the configuration file read for Syncron.
The file will live under ~/.config/ folder.
Prior to this, Syncron could only read from the path where it was now running.
fixes https://github.com/RedHatCRE/syncron/issues/25

### CODE REVIEW

File: pkg/bucketaws/setup.go [hunk 1]
```diff
@@ -53,10 +53,10 @@ func ProcessDate(fromDate time.Time) []string {
 // Reading from file syncron.yaml
 func ConfigRead() {
 
-	viper.SetConfigFile("syncron.yaml")
-	//viper.SetConfigType("yaml")
-	viper.AddConfigPath("./config")
-	//viper.AddConfigPath(".")
+	viper.SetConfigName("syncron")
+	viper.SetConfigType("yaml")
+	viper.AddConfigPath(".config/")
```
Comment (cescgina) [inline pkg/bucketaws/setup.go:58]: I don't know much about viper, but wouldn't this still be pointing to the working directory? Something like `$HOME/.config/` or similar should be used, unless viper does by default include the user home directory

Comment (IgnacioPro) [reply pkg/bucketaws/setup.go:58]: It does it by default yes.

Comment (cescgina) [reply pkg/bucketaws/setup.go:58]: TIL, then it should be all good

**Review by adrianfusco — APPROVED** [review]
+1

**Review by cescgina — APPROVED** [review]
