### PR TITLE
Fix for no items found

### LINKED ISSUE #30: "No items found for: []" when running without --filter flag

### PR DESCRIPTION
**Pull request by IgnacioPro**
Syncron was giving an error when --filter flag was not used. This PR fixes the issue.
closes https://github.com/RedHatCRE/syncron/issues/30

### CODE REVIEW

File: utils/filter/filter.go [hunk 1]
```diff
@@ -59,3 +65,11 @@ func removeDuplicates[T string | int](sliceList []T) []T {
 	}
 	return list
 }
+
+//func emptyFlag(flagSlice []string) []string {
```
Comment (adrianfusco) [inline utils/filter/filter.go]: If it won't be used we can remove it.

**Review by adrianfusco — APPROVED** [review]
+1

File: utils/filter/filter.go (hunk 1 above)
Comment (IgnacioPro) [reply utils/filter/filter.go]: Forgot to remove, thanks!
